export default {

  //--- sign in
  SIGN_IN: "SIGN_IN",
  AUTH_REQUEST_PENDING: "AUTH_REQUEST_PENDING",
  AUTH_REQUEST_SUCCESS: "AUTH_REQUEST_SUCCESS",
  AUTH_REQUEST_FAIL: "AUTH_REQUEST_FAIL",

  //--- logout
  LOGOUT: "LOGOUT",
  LOGOUT_REQUEST_SUCCESS: "LOGOUT_REQUEST_SUCCESS",

  //--- openSky
  GET_FLIGHTS: "GET_FLIGHTS",
  GET_FLIGHTS_PENDING: "GET_FLIGHTS_PENDING",
  GET_FLIGHTS_FAILED: "GET_FLIGHTS_FAILED",
  GET_FLIGHTS_SUCCESS: "GET_FLIGHTS_SUCCESS",
};
